{% set name = "model2vec" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/model2vec-{{ version }}.tar.gz
  sha256: 8f09086781660a8364b0bcadc601a06045a08f62985da90f50b703148f9b09e0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - setuptools-scm >=8
    - pip
  run:
    - python >={{ python_min }}
    - jinja2
    - joblib
    - numpy
    - rich
    - safetensors
    - setuptools
    - tokenizers >=0.20
    - tqdm  # 
# Extra: distill
    - pytorch
    - transformers
    - scikit-learn  # 
# Extra: inference
    - skops  # 
# Extra: onnx
    - onnx  # 
# Extra: train
    - lightning

test:
  imports:
    - model2vec
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: Fast State-of-the-Art Static Embeddings
  dev_url: https://github.com/MinishLab/model2vec
  license: MIT
  license_file: LICENSE
  home: https://github.com/MinishLab/model2vec

extra:
  recipe-maintainers:
    - AndreasAlbertQC
